### ISSUE TITLE
你好 为啥我显示插件载入失败  

### ISSUE THREAD

**Issue by AnaCna** [lyshark/LyScript#1]
安装Python包：pip install LyScript32 或者 pip install LyScript64    这个包在哪呢  插件载入失败是因为它吗

**Comment by lyshark** [comment]
您好，需要在cmd命令行执行pip install LyScript

**Comment by AnaCna** [comment]
还是不行啊  执行了 pip install LyScript32以后  打开还是载入失败    拜托解答下  我是个菜鸟 
![SW{_72HEN8`8{WQVZKN )}8](https://user-images.githubusercontent.com/104078276/164245601-5d47f36a-648e-4351-a852-6edb48df4711.png)

**Comment by AnaCna** [comment]
![图片](https://user-images.githubusercontent.com/104078276/164247669-ce83d16c-b436-4782-9090-a2ea8dad3e27.png)
![图片](https://user-images.githubusercontent.com/104078276/164247732-7f68b26c-8f4a-426c-8407-03d64c044134.png)
![图片](https://user-images.githubusercontent.com/104078276/164247825-b59ccb4c-0a06-49cf-b6b0-55560f752eef.png)
放进去了 您看看

**Comment by lyshark** [comment]
下载最新版

**Comment by lyshark** [comment]
最新版的x64dbg，已经测试过不会有任何问题

**Comment by AnaCna** [comment]
感谢感谢  已经可以了    麻烦你这么耐心给我解答了
