### ISSUE TITLE
64位插件在VMWare虚拟机导致虚拟机卡死

### ISSUE THREAD

**Issue by Fourilace** [lyshark/LyScript#12]
尊敬的作者您好，我在物理机上安装了您的插件，使用体验非常棒！但是在Win10虚拟机上安装插件以后却导致X64dbg无法运行，而且在一两秒之后整个系统失去响应，请问该如何解决？

**Comment by lyshark** [comment]
您好，正常情况下是不会出现问题的，是否是其他插件与本插件冲突呢？因为在上线时我都经过了测试，并没有出现您所说的这种情况。
