### ISSUE TITLE
get_all_breakpoint 出现struct.error

### ISSUE THREAD

**Issue by iewgnaw** [lyshark/LyScript#16]
调用get_all_breakpoint， 经常返回False， 我把内部的exception logging下来发现是struct.error。
这个问题也不是必定出现，多跑几次可能可能又有正常情况。

```
ERROR:root:unpack requires a buffer of 24 bytes
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\LyScript64\__init__.py", line 326, in get_all_breakpoint
    (address,enabled,hitcount,type) = struct.unpack("< q q i i",recv_bp)
struct.error: unpack requires a buffer of 24 bytes
```

- 操作系统: windows10   64位
- x64dbg 和LyScript都是readme中链接下载的，换了其他版本，也会出现以上情况。

请问这是什么问题？

**Comment by lyshark** [comment]
@iewgnaw 抱歉给您造成了困扰，目前该项目正在准备重新开发，因为在以往开发时过于仓促并没有考虑的很周到，这个问题应该是数据包并没有及时收到造成的，请给我一段时间我会重新开发规范化，并公开完整源代码。
