### ISSUE TITLE
script_runcmd_ex error

### ISSUE THREAD

**Issue by xiaoyaod** [lyshark/LyScript#17]
64位程序 dbg.script_runcmd_ex('rip') 返回的数据为b'rip'  b''  b''  b''  b''  0  125649873  0  0  0  5002  0  0 （将收到的数据打印出来了）
print(dbg.get_thread_list()) 可以加线程信息打印出来
换个程序 dbg.script_runcmd_ex('rip') 可以得到正确的值

**Comment by dlupx** [comment]
x64dbg.exe (Apr 11 2024 )
script_runcmd_ex() function always return false
