### ISSUE TITLE
遍历模块导入表或者导出表时，如果其中某个模块导入表/导出表为空，返回值是false.再调用get_module_import或者export访问其它模块，返回值也会出错。

### ISSUE THREAD

**Issue by pexufe123** [lyshark/LyScript#20]
测试发现，遍历模块导入表或者导出表时，如果其中某个模块导入表/导出表为空，返回值是false。再调用get_module_import或者export访问其它模块，返回值也会出错。后来发现在返回值false的同时，dbg.is_connect()也变成false了，需要重新再执行一次dbg.connect()后，get_module_import/export才能返回正确结果。

**Comment by lyshark** [comment]
感谢反馈
