### ISSUE TITLE
DebugControl.script_initdebug 的路径需要用引号包起来

### ISSUE THREAD

**Issue by noword** [lyshark/LyScript#8]
LyScriptTools64/LyScriptTools64/__init__.py 1905行
LyScriptTools32/LyScriptTools32/__init__.py 1634行

```return self.dbg.run_command_exec(f"InitDebug {path}")```

需要改成
 ```return self.dbg.run_command_exec(f'InitDebug "{path}"')```

否则如果路径中含有空格的话，就无法正常打开。

**Comment by lyshark** [comment]
感谢，我改一下
