### ISSUE TITLE
set_debug("StepOut") 和 script_stepout()  期待效果是F8步过，实际运行时都是执行到返回（效果是Ctrl+F9）

### ISSUE THREAD

**Issue by ken1691** [lyshark/LyScript#9]
set_debug("StepOut") 和 script_stepout()  这两条在文档内描述的是F8普通步过，运行的时候都是执行到返回。

刚接触您的插件，不知道是本身就这样，还是x32dbg升级后产生的问题。

请问还有其它方法执行普通步过吗（按F8的效果）？

**Comment by ken1691** [comment]
找到了。
dbg.run_command_exec("step")

**Comment by lyshark** [comment]
> 找到了。 dbg.run_command_exec("step")

抱歉，刚刚看到您的回复，您可以使用这个命令自定义执行，这个问题我记下了，后期会更新上，感谢您的支持。
